name: todark
description: Task management application

publish_to: "none"

version: 1.5.1+41

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  path: ^1.9.0
  intl: ^0.19.0
  isar: 
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  iconsax: ^0.0.8
  timezone: ^0.9.3
  workmanager: ^0.5.2
  home_widget: ^0.6.0
  file_picker: ^8.0.3
  restart_app: ^1.2.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  time_machine: ^0.9.17
  bottom_picker: ^2.7.0
  dynamic_color: ^1.7.0
  path_provider: ^2.1.3
  table_calendar: ^3.1.1
  flutter_timezone: ^1.0.8
  package_info_plus: ^8.0.0
  flex_color_picker: ^3.5.0
  isar_flutter_libs:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.6.0
  sleek_circular_slider: ^2.0.1
  flutter_local_notifications: ^17.1.2
  android_intent_plus: ^5.0.2
  flutter_animate: ^4.5.0
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1


flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/
